import { createAPIPage } from 'fumadocs-openapi/ui';
import { openapi } from '@/lib/openapi';

/**
 * Renders the pages generated by scripts/gen-openapi-docs.mjs. `createAPIPage`
 * resolves the `document` id itself (matching `lib/openapi.ts`'s `input`), so
 * no manual bridging is needed here.
 */
export const APIPage = createAPIPage(openapi, {
  playground: {
    // The API is pre-release and has no reachable server (see
    // openapi/README.md and the landing page) — a "send request" panel would
    // either silently fail or, worse, hit whatever happens to be listening on
    // a reader's own localhost:8787. Keep the static schema/example explorer,
    // drop the live-request UI so the page can't imply a callable endpoint.
    enabled: false,
  },
});
