#!/usr/bin/env node
/**
 * gen-docs: regenerate content/docs/reference/functions/ from the engine's
 * functions.json registry (single source of truth, lives in truecalc/core).
 *
 * CI runs this and fails on drift (`git diff --exit-code`), so generated pages
 * must never be edited by hand.
 *
 * PINNED_CORE_REF: the git ref of truecalc/core that functions.json is fetched
 * from. TODO(version-pin): point this at the release tag matching the
 * @truecalc/core version pinned in package.json once functions.json is
 * populated and tagged (it is currently an empty array on main; see
 * truecalc/core#14).
 */
import { mkdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Advance via version-bump PRs only (CLAUDE.md version-pin rule).
const PINNED_CORE_REF = '57964975b79e7326c3b69ab21d53119171767e05';
const FUNCTIONS_JSON_URL =
  process.env.FUNCTIONS_JSON_URL ??
  `https://raw.githubusercontent.com/truecalc/core/${PINNED_CORE_REF}/functions.json`;

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'content', 'docs', 'reference', 'functions');

/** Escape characters that MDX would treat as JSX/expressions. */
function mdxEscape(text) {
  return String(text ?? '')
    .replaceAll('{', '&#123;')
    .replaceAll('}', '&#125;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function slugify(name) {
  return String(name).toLowerCase().replace(/[^a-z0-9]+/g, '-');
}

function functionPage(fn) {
  const lines = [];
  lines.push('---');
  lines.push(`title: ${fn.name}`);
  const desc = String(fn.description ?? '').replaceAll('\n', ' ').trim();
  lines.push(`description: ${JSON.stringify(desc)}`);
  const fnName = String(fn.name)
  const seoTitle = `${fnName}: Spreadsheet Function in Google Sheets & Excel`
  const seoDesc = `TrueCalc \`${fnName}\` — conformant with Google Sheets and Excel. ${desc.slice(0, 100)}`.slice(0, 160)
  const llmsDesc = `TrueCalc ${fnName} function: ${desc.slice(0, 120)} Google Sheets/Excel conformant with fixture-verified behavior.`.slice(0, 200)
  lines.push(`seoTitle: ${JSON.stringify(seoTitle)}`)
  lines.push(`seoDescription: ${JSON.stringify(seoDesc)}`)
  lines.push(`llmsDescription: ${JSON.stringify(llmsDesc)}`)
  lines.push('---');
  lines.push('');
  lines.push(
    '{/* GENERATED by scripts/gen-docs.mjs from functions.json — do not edit. */}',
  );
  lines.push('');
  if (fn.syntax) {
    lines.push('## Syntax');
    lines.push('');
    lines.push('```');
    lines.push(String(fn.syntax));
    lines.push('```');
    lines.push('');
  }
  if (Array.isArray(fn.arguments) && fn.arguments.length > 0) {
    lines.push('## Arguments');
    lines.push('');
    lines.push('| Name | Type | Required | Description |');
    lines.push('| --- | --- | --- | --- |');
    for (const a of fn.arguments) {
      lines.push(
        `| \`${mdxEscape(a.name)}\` | ${mdxEscape(a.type)} | ${a.required ? 'yes' : 'no'} | ${mdxEscape(a.description)} |`,
      );
    }
    lines.push('');
  }
  if (fn.returns) {
    lines.push('## Returns');
    lines.push('');
    lines.push(`${mdxEscape(fn.returns.type)} — ${mdxEscape(fn.returns.description)}`);
    lines.push('');
  }
  if (Array.isArray(fn.examples) && fn.examples.length > 0) {
    lines.push('## Examples');
    lines.push('');
    lines.push('```formula');
    for (const ex of fn.examples) {
      lines.push(`${ex.formula} // => ${ex.result}`);
    }
    lines.push('```');
    lines.push('');
  }
  if (Array.isArray(fn.errors) && fn.errors.length > 0) {
    lines.push('## Errors');
    lines.push('');
    for (const e of fn.errors) lines.push(`- ${mdxEscape(e)}`);
    lines.push('');
  }
  if (fn.notes) {
    lines.push('## Notes');
    lines.push('');
    lines.push(mdxEscape(fn.notes));
    lines.push('');
  }
  return lines.join('\n');
}

async function main() {
  let raw;
  if (process.env.FUNCTIONS_JSON_FILE) {
    raw = readFileSync(process.env.FUNCTIONS_JSON_FILE, 'utf8');
  } else {
    const res = await fetch(FUNCTIONS_JSON_URL);
    if (!res.ok) {
      throw new Error(`Failed to fetch ${FUNCTIONS_JSON_URL}: HTTP ${res.status}`);
    }
    raw = await res.text();
  }
  const functions = JSON.parse(raw);
  if (!Array.isArray(functions)) {
    throw new Error('functions.json must be a JSON array');
  }
  functions.sort((a, b) => {
    const an = String(a.name);
    const bn = String(b.name);
    return an < bn ? -1 : an > bn ? 1 : 0;
  });

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const slugs = [];
  for (const fn of functions) {
    if (!fn || typeof fn.name !== 'string' || fn.name.length === 0) {
      throw new Error(`Invalid registry entry: ${JSON.stringify(fn)}`);
    }
    const slug = slugify(fn.name);
    if (slugs.includes(slug)) throw new Error(`Duplicate function slug: ${slug}`);
    slugs.push(slug);
    writeFileSync(join(outDir, `${slug}.mdx`), functionPage(fn) + '\n');
  }

  const indexBody = [
    '---',
    'title: Functions',
    `description: "Reference pages for every TrueCalc function, generated from the engine's functions.json registry."`,
    '---',
    '',
    '{/* GENERATED by scripts/gen-docs.mjs from functions.json — do not edit. */}',
    '',
    functions.length === 0
      ? `The function registry (\`functions.json\` in truecalc/core at \`${PINNED_CORE_REF}\`) is not populated yet — function pages will appear here automatically once it is (tracked in truecalc/core#14).`
      : `${functions.length} functions. Generated from \`functions.json\` in truecalc/core at \`${PINNED_CORE_REF}\`.`,
    '',
  ].join('\n');
  writeFileSync(join(outDir, 'index.mdx'), indexBody + '\n');

  writeFileSync(
    join(outDir, 'meta.json'),
    JSON.stringify({ title: 'Functions', pages: ['index', ...slugs] }, null, 2) + '\n',
  );

  console.log(`gen-docs: wrote ${functions.length} function page(s) + index to ${outDir}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
