#!/usr/bin/env node
/**
 * sync-openapi: vendor a fresh copy of the REST API's openapi.json into this
 * repo, then regenerate the reference pages from it.
 *
 * This site is public; the API contract is generated in a private repo, so it
 * cannot be fetched at build time. Instead we vendor a point-in-time copy
 * (openapi/rest-api.json) and commit it. This script is the ONLY supported
 * way to refresh that copy — see openapi/README.md for the full picture,
 * including what does and does not guard against it going stale.
 *
 * Usage:
 *   node scripts/sync-openapi.mjs <path-to-openapi.json>
 *   API_CONTRACT_OPENAPI_PATH=<path-to-openapi.json> node scripts/sync-openapi.mjs
 *
 * <path-to-openapi.json> is a local filesystem path to the generated
 * openapi.json from wherever the API contract package lives on your machine.
 * This script deliberately takes that path as an argument/env var rather than
 * hard-coding it, so this repo never has to name that other repo.
 */
import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const vendoredPath = join(root, 'openapi', 'rest-api.json');
const readmePath = join(root, 'openapi', 'README.md');

const sourcePath = process.argv[2] ?? process.env.API_CONTRACT_OPENAPI_PATH;

if (!sourcePath) {
  console.error(
    [
      'Usage: node scripts/sync-openapi.mjs <path-to-openapi.json>',
      '   or: API_CONTRACT_OPENAPI_PATH=<path-to-openapi.json> node scripts/sync-openapi.mjs',
      '',
      'Point it at the openapi.json generated by the API contract package',
      '(wherever you have it checked out locally). See openapi/README.md.',
    ].join('\n'),
  );
  process.exit(1);
}

if (!existsSync(sourcePath)) {
  console.error(`No file at ${sourcePath}`);
  process.exit(1);
}

const raw = readFileSync(sourcePath, 'utf8');
let doc;
try {
  doc = JSON.parse(raw);
} catch (err) {
  console.error(`${sourcePath} is not valid JSON: ${err.message}`);
  process.exit(1);
}

if (typeof doc.openapi !== 'string' || !doc.openapi.startsWith('3.')) {
  console.error(`${sourcePath} does not look like an OpenAPI 3.x document (openapi: ${doc.openapi})`);
  process.exit(1);
}

// Copy bytes as-is (not re-serialized) so the vendored file's diff against its
// source is exactly "what changed upstream" — nothing reformatted by us.
copyFileSync(sourcePath, vendoredPath);

const sha256 = createHash('sha256').update(raw).digest('hex').slice(0, 12);
const syncedAt = new Date().toISOString().slice(0, 10);
const specVersion = doc.info?.version ?? 'unknown';
const specTitle = doc.info?.title ?? 'unknown';

const stamp = [
  '<!-- LAST-SYNCED:START — updated by scripts/sync-openapi.mjs, do not hand-edit -->',
  '',
  `- Spec title: \`${specTitle}\``,
  `- Spec version: \`${specVersion}\``,
  `- Vendored on: ${syncedAt}`,
  `- SHA-256 (first 12 hex chars): \`${sha256}\``,
  '',
  '<!-- LAST-SYNCED:END -->',
].join('\n');

const readme = readFileSync(readmePath, 'utf8');
const stamped = readme.replace(
  /<!-- LAST-SYNCED:START.*?LAST-SYNCED:END -->/s,
  stamp,
);
if (stamped === readme) {
  console.error('Could not find the LAST-SYNCED markers in openapi/README.md — refusing to guess where to write the stamp.');
  process.exit(1);
}
writeFileSync(readmePath, stamped);

console.log(`Vendored ${specTitle} ${specVersion} (${sha256}) from ${sourcePath}`);
console.log('Regenerating reference pages...');

execFileSync(process.execPath, [join(root, 'scripts', 'gen-openapi-docs.mjs')], {
  stdio: 'inherit',
  cwd: root,
});

console.log('\nDone. Review the diff, then commit openapi/ and content/docs/api/rest/ together.');
